apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cnc.fullname" . }}-api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: {{ include "cnc.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "cnc.fullname" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: 8000
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: 8000
          resources:
            limits:
              cpu: {{ .Values.resources.api.limits.cpu }}
              memory: {{ .Values.resources.api.limits.memory }}

