apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cnc.fullname" . }}-worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: {{ include "cnc.fullname" . }}-worker
  template:
    metadata:
      labels:
        app: {{ include "cnc.fullname" . }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery","-A","app.tasks.worker","worker","-Q","cpu,postproc","-c","4"]
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.worker.limits.cpu }}
              memory: {{ .Values.resources.worker.limits.memory }}

