apiVersion: v1
kind: Service
metadata:
  name: {{ include "cnc.fullname" . }}-api
spec:
  selector:
    app: {{ include "cnc.fullname" . }}-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

