name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./proje/apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .[dev]
      - name: Lint (ruff)
        run: ruff .
      - name: Format check (black)
        run: black --check .
      - name: Type check (mypy)
        run: mypy app || true
      - name: Pytest + Coverage
        run: |
          pytest --maxfail=1 -q --cov=app --cov-report=xml --cov-report=term
          python - << 'PY'
import sys
import xml.etree.ElementTree as ET
tree=ET.parse('coverage.xml');root=tree.getroot()
rate=float(root.attrib.get('line-rate','0'))
print('coverage line-rate=', rate)
sys.exit(0 if rate>=0.75 else 1)
PY
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage-xml
          path: proje/apps/api/coverage.xml

  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./proje/apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
      - name: Install deps
        run: pnpm install
      - name: Lint
        run: pnpm lint || true
      - name: Type check
        run: pnpm typecheck || true
      - name: Tests
        run: pnpm test || true
      - name: Playwright install
        run: npx playwright install --with-deps
      - name: E2E
        run: |
          echo "(E2E yeri, backend gerektirir; ayrı iş akışında koşturulabilir)"
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install API deps
        working-directory: ./apps/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint API
        working-directory: ./apps/api
        run: |
          ruff check .
          black --check .
          isort --check-only .

      - name: Test API
        working-directory: ./apps/api
        env:
          DATABASE_URL: sqlite+pysqlite:///:memory:
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing

      - name: Install Web deps
        working-directory: ./apps/web
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          pnpm install

      - name: Lint Web
        working-directory: ./apps/web
        run: pnpm eslint .

      - name: Test Web
        working-directory: ./apps/web
        run: pnpm test


